# Generated by Django 5.2.7 on 2025-10-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('diretor', models.CharField(max_length=100, verbose_name='Diretor')),
                ('ano_lancamento', models.IntegerField(verbose_name='Ano de Lançamento')),
                ('genero', models.CharField(max_length=50, verbose_name='Gênero')),
                ('duracao', models.IntegerField(verbose_name='Duração (minutos)')),
                ('sinopse', models.TextField(blank=True, verbose_name='Sinopse')),
            ],
            options={
                'verbose_name': 'Filme',
                'verbose_name_plural': 'Filmes',
            },
        ),
    ]
