# Generated by Django 5.2.7 on 2025-10-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to='capas_filmes/', verbose_name='Capa do Filme'),
        ),
    ]
